on:
  push:

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render in docs folder
        run: >
            find * -type f -name _quarto.yml -print0 | 
                while IFS= read -r -d '' LINE; do 
                    FOLDER=$(dirname "$LINE")
                    mkdir -p "_site/$FOLDER"
                    quarto render "$FOLDER/slides.qmd"
                    mv "$FOLDER/slides.html" "_site/$FOLDER/slides.html"
                done
      - name: Publish slides
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}