on:
  push:
    branches:
      - "main"

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: pages
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render in docs folder
        run: >
            find main/* -type f -name _quarto.yml -print0 | 
                while IFS= read -r -d '' LINE; do 
                    FOLDER=$(dirname "$LINE")
                    mkdir -p "_site/$FOLDER"
                    quarto render --quiet "$FOLDER/slides.qmd"
                    mv "$FOLDER/slides.html" "_site/$FOLDER/slides.html"
                done
      - name: Move rendered slides
        run: mv -f -r main/_site/* pages/
      - name: Publish slides
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd pages
          git add -A .
          git commit -m "Publish rendered slides"
          git push